# Generated by Django 4.2.7 on 2023-11-27 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskmanager",
            name="tasks",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_tasks",
                through="main.Task",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
